Lots of mostly DNS related changes
dnsbl.{c,h}:
- Many changes to accomdate configurable output from blacklists
- Return values from DNSBLs must now be set in the configuration file,
  they are not hardcoded
- It is possible to ignore some of the results returned from DNSBLs
- Lookup errors are now sent to channels as errors as well as to the log
- The void pointer passed to firedns is now a dnsbl_scan struct (contains
  a pointer to the blacklist and to the scan_struct).

firedns.{c,h}:
- firedns.conf is now read from the BOPM configuration dir
  (etc/firedns.conf) not the system wide /etc.
  (firedns.conf is just a list of IP addresses, one on each line)
- Fixes to make firedns.conf work in a sane way
- Better errors when problems occur reading configuration files
- firedns_resolveip4 fixed to actually work
- new error: Network error, for errors receiving from the dns server

inet.{c,h}, irc.c, scan.c, main.c:
- bopm_gethostbyname removed, code uses firedns_resolveip4 now
- DNS lookup code adjusted to use firedns

scan.c:
- %t in kline format strings - the type of proxy found on the host
  works for both DNSBL results and proxies found by BOPM

configuation:
- Added new blacklist directives (this breaks old config files).
- scanner blocks now inherit settings from _the one above them_,
  this saves multiple definitions of the same thing in different
  scanner blocks (this affects vhost, fd, target_ip, target_port,
  timeout, max_read and target_strning in scanner blocks).